"""
Relational GNN Specialist Agent.

This agent is responsible for generating and executing GNN training scripts
that use the relbench.modeling modules for training on relational data.

The agent takes the Dataset and Task classes generated by DatasetBuilder 
and TaskBuilder agents, and creates a complete training pipeline.
"""

import logging
from typing import Optional, Callable, Any

from smolagents import CodeAgent, LiteLLMModel

from plexe.config import config
from plexe.internal.common.utils.agents import get_prompt_templates
from plexe.tools.gnn_training_script_generator import (
    get_training_script_template,
    generate_training_script,
    execute_training_script,
    get_dataset_task_info_from_registry,
    validate_training_prerequisites,
)
from plexe.tools.interaction import save_to_workdir

logger = logging.getLogger(__name__)


class RelationalGNNSpecialistAgent:
    """
    Agent for training GNNs on Relational Entity Graphs using the RelBench framework.
    
    This agent generates training scripts that:
    1. Load custom Dataset and Task classes from previous agents
    2. Build heterogeneous graphs using make_pkey_fkey_graph
    3. Use HeteroEncoder, HeteroTemporalEncoder, HeteroGraphSAGE for modeling
    4. Train with temporal sampling to prevent data leakage
    5. Evaluate and save the best model
    """

    def __init__(
        self,
        model_id: str | None = None,
        verbose: bool = False,
        chain_of_thought_callable: Optional[Callable] = None,
    ):
        """
        Initialize the Relational GNN Specialist Agent.

        Args:
            model_id: Model ID for the LLM
            verbose: Whether to display detailed agent logs
            chain_of_thought_callable: Optional callback for chain-of-thought logging
        """
        self.model_id = model_id or "gpt-4o"
        self.verbosity = 1 if verbose else 0

        self.agent = CodeAgent(
            name="RelationalGNNSpecialist",
            description=(
                "Expert in Graph Neural Networks for Relational Deep Learning. "
                "Generates and executes training scripts using relbench.modeling modules "
                "(make_pkey_fkey_graph, HeteroEncoder, HeteroTemporalEncoder, HeteroGraphSAGE). "
                "Works with Dataset and Task classes from DatasetBuilder and TaskBuilder agents."
            ),
            model=LiteLLMModel(model_id=self.model_id),
            tools=[
                # Information retrieval
                get_dataset_task_info_from_registry,
                get_training_script_template,
                # Validation
                validate_training_prerequisites,
                # Script generation
                generate_training_script,
                # Execution
                execute_training_script,
                # File saving
                save_to_workdir,
            ],
            prompt_templates=get_prompt_templates(
                base_template_name="code_agent.yaml",
                override_template_name="relational_gnn_specialist_prompt_templates.yaml",
            ),
            verbosity_level=self.verbosity,
            add_base_tools=False,
            additional_authorized_imports=config.code_generation.authorized_agent_imports
            + [
                "plexe",
                "plexe.*",
                "pandas",
                "pandas.*",
                "numpy",
                "numpy.*",
                "torch",
                "torch.*",
                "torch_geometric",
                "torch_geometric.*",
                "torch_frame",
                "torch_frame.*",
                "relbench",
                "relbench.*",
            ],
            step_callbacks=[chain_of_thought_callable],
        )

    def run(self, task_description: str) -> Any:
        """
        Run the agent to generate and execute GNN training.
        
        Args:
            task_description: Description of the training task including:
                - Path to dataset module (or will retrieve from registry)
                - Path to task module (or will retrieve from registry)
                - Training configuration (epochs, batch_size, etc.)
                - Task type (regression, classification)
                
        Returns:
            Result of the training process
        """
        return self.agent.run(task_description)
